name: open_weather_map
description: An app to display the current weather using OpenWeatherMap API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  # Functional programming goodies
  dartz: ^0.9.2

  # A helper for instance comparisons
  equatable: ^1.2.5

  # Service locator
  get_it: ^5.0.1

  # Conectivity services for Android and iOS
  data_connection_checker: ^0.3.4

  # HTTP Client
  dio: ^3.0.10

  # Cache solution
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.6

  # Dart package for tests
  test: ^1.15.5

  # Package that mocks abstract classes
  mockito: ^4.1.3

flutter:
  uses-material-design: true